spring:
  application:
    name: SPS-ACAD-TITLE-MASTER-DATA
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin 
  datasource:
    url: jdbc:mysql://GBSMIXDEV01.UK.OUP.COM:3306/sps
    username: SMIXDBUser
    password: P@ssw0rd1!
    driver-class-name: com.mysql.jdbc.Driver  
      
server:
  port: 8080  
eureka:
  client:
    enabled: false
    
activemq:
    us:
      queuename: queue:SPS-ACAD-US-US81-STAR-TITLE-MASTER-DEV
      corntab:
        timezone: US/Hawaii
        starttime: 0 01 00 ? * * *
        stoptime: 0 59 23 ? * * *
scheduler:
   route:
     autoStartup: true
     completionTimeout: 10000

file:
  backup:
    location: C:\\JavaTest\\SPS\\AC20_FirstCosts\\   
       
ftp:
  us: 
    server: uscarsappdc01.us.oup.com
    port: 21
    username: USOUP\us_oxfordpublish
    password: EWvqG517
    drop:
      location: /R2Q400/ABC/IN/
      
management:
  security:
    enabled: false
  metrics:
    export:
      prometheus: 
        enabled: true
    distribution:
      percentiles[http.server.requests]: 0.95, 0.99
      percentiles-histogram[http.server.requests]: true
      sla[http.server.requests]: 10ms, 100ms

---
spring:
  profiles: dev
  activemq:
    broker-url: tcp://gbsmixdev01.uk.oup.com:63636
    user: servicemix
    password: servicemix@1234

activemq:
    us:
      queuename: queue:SPS-ACAD-US-US81-STAR-TITLE-MASTER-DEV
      corntab:
        timezone: US/Hawaii
        starttime: 0 0,10,20,30,40,50 * * * ? *
        stoptime: 0 9,19,29,39,49,59 * * * ? *
scheduler:
   route:
     autoStartup: true
     completionTimeout: 10000
      
file:
  backup:
    location: /OUT/SPS/${spring.application.name}/dev
    
ftp:
  us: 
    server: uscarsappdc01.us.oup.com
    port: 21
    username: USOUP\us_oxfordpublish
    password: EWvqG517
    drop:
      location: /R2Q400/ABC/IN/
    
eureka:
  client:
    enabled: true
    service-url:  
      defaultZone: http://dev-oupeureka:8761/eureka/
  instance:
    prefer-ip-address: true   

management:
  security:
    enabled: false
  metrics:
    export:
      prometheus: 
        enabled: true
    distribution:
      percentiles[http.server.requests]: 0.95, 0.99
      percentiles-histogram[http.server.requests]: true
      sla[http.server.requests]: 10ms, 100ms
      
---
spring:
  profiles: uat
  activemq:
    broker-url: tcp://gboxfamqdev001.uk.oup.com:61616
    user: servicemix
    password: servicemix@1234
  
activemq:
    us:
      queuename: queue:SPS-ACAD-US-US81-STAR-TITLE-MASTER-QA
      corntab:
        starttime: 0 0,10,20,30,40,50 * * * ? *
        stoptime: 0 9,19,29,39,49,59 * * * ? *
        
scheduler:
   route:
     autoStartup: true
     completionTimeout: 10000
        
file:
  backup:
    location: /OUT/SPS/${spring.application.name}/uat
    
ftp:
  us: 
    server: uscarsappdc01.us.oup.com
    port: 21
    username: USOUP\us_oxfordpublish
    password: EWvqG517
    drop:
      location: /R2Q400/ABC/IN/
    
eureka:
  client:
    enabled: true
    service-url:  
      defaultZone: http://uat-oupeureka:8761/eureka/
  instance:
    prefer-ip-address: true    
    
management:
  security:
    enabled: false
  metrics:
    export:
      prometheus: 
        enabled: true
    distribution:
      percentiles[http.server.requests]: 0.95, 0.99
      percentiles-histogram[http.server.requests]: true
      sla[http.server.requests]: 10ms, 100ms
---
spring:
  profiles: prod
  activemq:
    broker-url: tcp://gbsmixprd02.uk.oup.com:63636
    user: servicemix
    password: servicemix@1234

activemq:
    uk:
      queuename: queue:SPS-ACAD-TITLE-MASTER-DATA-PRD
      
file:
  backup:
    location: /OUT/SPS/${spring.application.name}/prod
    
ftp:
  us: 
    server: uscarsappdc01.us.oup.com
    port: 21
    username: USOUP\us_oxfordpublish
    password: EWvqG517
    drop:
      location: /R2Q400/ABC/IN/
    
management:
  security:
    enabled: false
  metrics:
    export:
      prometheus: 
        enabled: true
    distribution:
      percentiles[http.server.requests]: 0.95, 0.99
      percentiles-histogram[http.server.requests]: true
      sla[http.server.requests]: 10ms, 100ms
       
